"""Context pack loader for agent execution.

Loads context packs from the filesystem that contain relevant code
and metadata for agent execution. Context packs are generated by
the Repo Mapper agent.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from src.core.exceptions import ASDLCError

logger = logging.getLogger(__name__)


class ContextPackNotFoundError(ASDLCError):
    """Raised when a context pack is not found."""

    pass


class ContextPackFormatError(ASDLCError):
    """Raised when a context pack has invalid format."""

    pass


class ContextLoader:
    """Loads context packs from the filesystem.

    Context packs contain the relevant code files and metadata
    that agents need for execution. They are typically generated
    by the Repo Mapper agent.

    Example:
        loader = ContextLoader(workspace_path="/app/workspace")
        pack = await loader.load(task_id="task-123")
        files = pack["files"]
    """

    CONTEXT_PACKS_DIR = "context_packs"

    def __init__(
        self,
        workspace_path: str,
        validate: bool = False,
    ) -> None:
        """Initialize the context loader.

        Args:
            workspace_path: Path to the workspace directory.
            validate: Whether to validate context pack structure.
        """
        self._workspace_path = Path(workspace_path)
        self._validate = validate

    @property
    def workspace_path(self) -> str:
        """Return the workspace path as a string."""
        return str(self._workspace_path)

    def get_context_pack_path(self, task_id: str) -> str:
        """Get the path to a context pack file.

        Args:
            task_id: The task identifier.

        Returns:
            str: Full path to the context pack file.
        """
        return str(
            self._workspace_path / self.CONTEXT_PACKS_DIR / f"{task_id}.json"
        )

    async def exists(self, task_id: str) -> bool:
        """Check if a context pack exists for a task.

        Args:
            task_id: The task identifier.

        Returns:
            bool: True if the context pack exists.
        """
        path = Path(self.get_context_pack_path(task_id))
        return path.exists()

    async def load(self, task_id: str) -> dict[str, Any]:
        """Load a context pack for a task.

        Args:
            task_id: The task identifier.

        Returns:
            dict: The context pack data.

        Raises:
            ContextPackNotFoundError: If the pack doesn't exist.
            ContextPackFormatError: If the pack has invalid format.
        """
        path = self.get_context_pack_path(task_id)
        return await self.load_from_path(path)

    async def load_from_path(self, path: str) -> dict[str, Any]:
        """Load a context pack from a specific path.

        Args:
            path: Full path to the context pack file.

        Returns:
            dict: The context pack data.

        Raises:
            ContextPackNotFoundError: If the file doesn't exist.
            ContextPackFormatError: If the file has invalid format.
        """
        file_path = Path(path)

        if not file_path.exists():
            raise ContextPackNotFoundError(
                f"Context pack not found: {path}",
                details={"path": path},
            )

        try:
            content = file_path.read_text()
            data = json.loads(content)
        except json.JSONDecodeError as e:
            raise ContextPackFormatError(
                f"Invalid JSON format in context pack: {e}",
                details={"path": path, "error": str(e)},
            ) from e

        if self._validate:
            self._validate_pack(data, path)

        logger.debug(f"Loaded context pack from: {path}")
        return data

    def _validate_pack(self, data: dict[str, Any], path: str) -> None:
        """Validate context pack structure.

        Args:
            data: The context pack data.
            path: Path for error reporting.

        Raises:
            ContextPackFormatError: If validation fails.
        """
        # Check required fields
        if "files" not in data:
            raise ContextPackFormatError(
                "Context pack missing required 'files' field",
                details={"path": path},
            )

        # Validate files is a list
        if not isinstance(data["files"], list):
            raise ContextPackFormatError(
                "Context pack 'files' must be a list",
                details={"path": path, "actual_type": type(data["files"]).__name__},
            )
