/**
 * EnvExportDialog Component (P05-F13 T30)
 *
 * Modal dialog for exporting LLM configuration to .env format.
 * Provides copy to clipboard and download as file functionality.
 */

import { useState, useMemo, useCallback, useRef, useEffect } from 'react';
import clsx from 'clsx';
import {
  XMarkIcon,
  ClipboardDocumentIcon,
  ArrowDownTrayIcon,
  CheckIcon,
  InformationCircleIcon,
} from '@heroicons/react/24/outline';
import type { AgentLLMConfig } from '../../types/llmConfig';

export interface EnvExportDialogProps {
  /** Whether dialog is open */
  open: boolean;
  /** Callback when dialog closes */
  onClose: () => void;
  /** Agent configurations to export */
  configs: AgentLLMConfig[];
  /** Custom class name */
  className?: string;
}

/**
 * Generate .env format content from agent configs
 */
function generateEnvContent(configs: AgentLLMConfig[]): string {
  const lines: string[] = [
    '# LLM Configuration - Generated by aSDLC Admin',
    '# Generated: ' + new Date().toISOString(),
    '',
  ];

  for (const config of configs) {
    const roleUpper = config.role.toUpperCase();
    const prefix = 'LLM_' + roleUpper;

    lines.push('# ' + config.role.charAt(0).toUpperCase() + config.role.slice(1) + ' Agent');
    lines.push(prefix + '_PROVIDER=' + config.provider);
    lines.push(prefix + '_MODEL=' + config.model);
    lines.push(prefix + '_API_KEY_ID=' + config.apiKeyId);
    lines.push(prefix + '_TEMPERATURE=' + config.settings.temperature);
    lines.push(prefix + '_MAX_TOKENS=' + config.settings.maxTokens);
    if (config.settings.topP !== undefined) {
      lines.push(prefix + '_TOP_P=' + config.settings.topP);
    }
    if (config.settings.topK !== undefined) {
      lines.push(prefix + '_TOP_K=' + config.settings.topK);
    }
    lines.push(prefix + '_ENABLED=' + (config.enabled ? 'true' : 'false'));
    lines.push('');
  }

  lines.push('# API Keys (IDs only - actual keys stored securely)');
  lines.push('# To use in deployment, set these environment variables:');
  lines.push('# ANTHROPIC_API_KEY=your-key-here');
  lines.push('# OPENAI_API_KEY=your-key-here');
  lines.push('# GOOGLE_API_KEY=your-key-here');

  return lines.join('\n');
}

export default function EnvExportDialog({
  open,
  onClose,
  configs,
  className,
}: EnvExportDialogProps) {
  const [copied, setCopied] = useState(false);
  const dialogRef = useRef<HTMLDivElement>(null);

  // Generate env content
  const envContent = useMemo(() => generateEnvContent(configs), [configs]);

  // Handle copy to clipboard
  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(envContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  }, [envContent]);

  // Handle download as file
  const handleDownload = useCallback(() => {
    const blob = new Blob([envContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'llm-config.env';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [envContent]);

  // Handle escape key and click outside
  useEffect(() => {
    if (!open) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };

    const handleClickOutside = (e: MouseEvent) => {
      if (dialogRef.current && !dialogRef.current.contains(e.target as Node)) {
        onClose();
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('mousedown', handleClickOutside);

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      data-testid="env-export-dialog"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      role="dialog"
      aria-modal="true"
      aria-labelledby="env-export-title"
    >
      <div
        ref={dialogRef}
        className={clsx(
          'w-full max-w-3xl max-h-[90vh] overflow-hidden',
          'bg-bg-secondary rounded-xl shadow-xl',
          'flex flex-col',
          className
        )}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border-primary">
          <h2
            id="env-export-title"
            className="text-lg font-semibold text-text-primary"
          >
            Export to .env Format
          </h2>
          <button
            data-testid="close-dialog-button"
            type="button"
            onClick={onClose}
            className="p-1 rounded hover:bg-bg-tertiary transition-colors"
            aria-label="Close dialog"
          >
            <XMarkIcon className="h-5 w-5 text-text-secondary" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto p-6 space-y-4">
          {/* Info banner */}
          <div className="flex items-start gap-3 p-3 rounded-lg bg-accent-blue/10 border border-accent-blue/30">
            <InformationCircleIcon className="h-5 w-5 text-accent-blue flex-shrink-0 mt-0.5" />
            <div className="text-sm">
              <p className="font-medium text-accent-blue">Security Note</p>
              <p className="text-text-secondary mt-1">
                API key IDs are exported, but not the actual keys. Configure the actual
                API keys separately in your deployment environment.
              </p>
            </div>
          </div>

          {/* Env content preview */}
          <pre
            data-testid="env-content-preview"
            className={clsx(
              'w-full p-4 rounded-lg',
              'font-mono text-sm leading-relaxed',
              'bg-bg-primary border border-border-primary',
              'text-text-primary',
              'overflow-auto max-h-80'
            )}
          >
            {envContent}
          </pre>
        </div>

        {/* Footer with actions */}
        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-border-primary">
          <button
            data-testid="copy-to-clipboard-button"
            type="button"
            onClick={handleCopy}
            className={clsx(
              'flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium',
              'border border-border-primary',
              'bg-bg-primary text-text-primary',
              'hover:bg-bg-tertiary transition-colors'
            )}
          >
            {copied ? (
              <>
                <CheckIcon className="h-4 w-4 text-status-success" />
                Copied!
              </>
            ) : (
              <>
                <ClipboardDocumentIcon className="h-4 w-4" />
                Copy to Clipboard
              </>
            )}
          </button>

          <button
            data-testid="download-file-button"
            type="button"
            onClick={handleDownload}
            className={clsx(
              'flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium',
              'bg-accent-teal text-white',
              'hover:bg-accent-teal/90 transition-colors'
            )}
          >
            <ArrowDownTrayIcon className="h-4 w-4" />
            Download as File
          </button>
        </div>
      </div>
    </div>
  );
}
