/**
 * RuleProposalsPage - Meta-HITL UI for reviewing and approving rule proposals
 *
 * Part of P05-F04: Adaptive Feedback Learning System.
 * Allows admins to review rule proposals generated by the Evaluator Agent.
 */

import { useState, useCallback } from 'react';
import {
  AdjustmentsHorizontalIcon,
  CheckCircleIcon,
  ExclamationTriangleIcon,
  FunnelIcon,
  LightBulbIcon,
} from '@heroicons/react/24/outline';
import { usePendingRules, useApproveRule, useRejectRule } from '@/api/feedback';
import type { RuleProposal, RuleType, PendingRulesParams } from '@/api/feedback';
import RuleProposalCard from '@/components/gates/RuleProposalCard';
import { Card, CardHeader, CardTitle, CardContent, EmptyState } from '@/components/common';
import { ToastContainer, useToast } from '@/components/common/Toast';

// Filter options
const agentOptions = [
  { value: '', label: 'All Agents' },
  { value: 'prd-agent', label: 'PRD Agent' },
  { value: 'design-agent', label: 'Design Agent' },
  { value: 'coding-agent', label: 'Coding Agent' },
  { value: 'review-agent', label: 'Review Agent' },
  { value: 'test-agent', label: 'Test Agent' },
];

const ruleTypeOptions = [
  { value: '', label: 'All Types' },
  { value: 'GUIDELINE', label: 'Guideline' },
  { value: 'CONSTRAINT', label: 'Constraint' },
  { value: 'POSITIVE_EXAMPLE', label: 'Positive Example' },
  { value: 'NEGATIVE_EXAMPLE', label: 'Negative Example' },
];

export default function RuleProposalsPage() {
  const [agentFilter, setAgentFilter] = useState('');
  const [typeFilter, setTypeFilter] = useState<RuleType | ''>('');
  const { toasts, showToast, removeToast } = useToast();

  // Build query params
  const params: PendingRulesParams = {};
  if (agentFilter) params.agent = agentFilter;
  if (typeFilter) params.ruleType = typeFilter as RuleType;

  const { data, isLoading, error } = usePendingRules(params);
  const approveRule = useApproveRule();
  const rejectRule = useRejectRule();

  // Handle approve
  const handleApprove = useCallback(
    (ruleId: string) => {
      approveRule.mutate(
        {
          ruleId,
          decision: 'approved',
          decidedBy: 'admin', // TODO: Get from auth context
        },
        {
          onSuccess: () => {
            showToast('Rule approved successfully', 'success');
          },
          onError: () => {
            showToast('Failed to approve rule', 'error');
          },
        }
      );
    },
    [approveRule, showToast]
  );

  // Handle modify (opens edit dialog - future enhancement)
  const handleModify = useCallback((ruleId: string) => {
    // TODO: Implement rule modification dialog
    console.log('Modify rule:', ruleId);
  }, []);

  // Handle reject
  const handleReject = useCallback(
    (ruleId: string) => {
      // TODO: Show dialog to capture rejection reason
      rejectRule.mutate(
        {
          ruleId,
          decision: 'rejected',
          decidedBy: 'admin', // TODO: Get from auth context
          reason: 'Rejected by admin',
        },
        {
          onSuccess: () => {
            showToast('Rule rejected', 'info');
          },
          onError: () => {
            showToast('Failed to reject rule', 'error');
          },
        }
      );
    },
    [rejectRule, showToast]
  );

  // Loading state
  if (isLoading) {
    return (
      <div className="space-y-6" data-testid="rule-proposals-page">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold text-text-primary">Rule Proposals</h1>
            <p className="text-text-secondary mt-1">
              Review and approve rule proposals from the Evaluator Agent
            </p>
          </div>
        </div>
        <div data-testid="loading-skeleton" className="space-y-4">
          {[1, 2, 3].map((i) => (
            <div
              key={i}
              className="h-48 bg-bg-secondary rounded-lg animate-pulse"
            />
          ))}
        </div>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="space-y-6" data-testid="rule-proposals-page">
        <EmptyState
          title="Failed to load rule proposals"
          description="An error occurred while loading the rule proposals. Please try again."
        />
      </div>
    );
  }

  const rules = data?.rules || [];
  const total = data?.total || 0;

  return (
    <div className="space-y-6" data-testid="rule-proposals-page">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-3">
            <LightBulbIcon className="h-8 w-8 text-accent-blue" />
            <h1 className="text-2xl font-semibold text-text-primary">Rule Proposals</h1>
          </div>
          <p className="text-text-secondary mt-1">
            Review and approve rule proposals from the Evaluator Agent
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-sm text-text-muted">Pending:</span>
          <span
            data-testid="proposal-count"
            className="px-2 py-0.5 bg-accent-blue/20 text-accent-blue rounded-full text-sm font-medium"
          >
            {total}
          </span>
        </div>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="py-3">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <FunnelIcon className="h-4 w-4 text-text-muted" />
              <span className="text-sm text-text-muted">Filters:</span>
            </div>
            <select
              data-testid="agent-filter"
              value={agentFilter}
              onChange={(e) => setAgentFilter(e.target.value)}
              className="px-3 py-1.5 bg-bg-tertiary border border-border-primary rounded text-sm text-text-primary focus:outline-none focus:border-accent-blue"
            >
              {agentOptions.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
            <select
              data-testid="type-filter"
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value as RuleType | '')}
              className="px-3 py-1.5 bg-bg-tertiary border border-border-primary rounded text-sm text-text-primary focus:outline-none focus:border-accent-blue"
            >
              {ruleTypeOptions.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
          </div>
        </CardContent>
      </Card>

      {/* Stats Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardContent className="py-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-accent-blue/10 rounded-lg">
                <AdjustmentsHorizontalIcon className="h-5 w-5 text-accent-blue" />
              </div>
              <div>
                <p className="text-sm text-text-muted">Total Proposals</p>
                <p className="text-xl font-semibold text-text-primary">{total}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="py-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-status-success/10 rounded-lg">
                <CheckCircleIcon className="h-5 w-5 text-status-success" />
              </div>
              <div>
                <p className="text-sm text-text-muted">High Confidence</p>
                <p className="text-xl font-semibold text-text-primary">
                  {rules.filter((r) => r.confidence >= 0.85).length}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="py-4">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-status-warning/10 rounded-lg">
                <ExclamationTriangleIcon className="h-5 w-5 text-status-warning" />
              </div>
              <div>
                <p className="text-sm text-text-muted">Medium Risk</p>
                <p className="text-xl font-semibold text-text-primary">
                  {rules.filter((r) => r.impact.riskLevel === 'medium' || r.impact.riskLevel === 'high').length}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Rule List */}
      {rules.length === 0 ? (
        <div data-testid="empty-state">
          <EmptyState
            title="No pending rule proposals"
            description="All rule proposals have been reviewed. New proposals will appear here when the Evaluator Agent detects patterns in HITL feedback."
          />
        </div>
      ) : (
        <div className="space-y-4">
          {rules.map((rule) => (
            <RuleProposalCard
              key={rule.id}
              proposal={{
                id: rule.id,
                title: rule.title,
                description: rule.description,
                proposedBy: rule.proposedBy,
                proposedAt: rule.proposedAt,
                affectedAgents: rule.affectedAgents,
                evidenceCount: rule.evidenceCount,
                evidence: rule.evidence,
                impact: rule.impact,
              }}
              onApprove={handleApprove}
              onModify={handleModify}
              onReject={handleReject}
            />
          ))}
        </div>
      )}

      {/* Toast notifications */}
      <ToastContainer toasts={toasts} onRemove={removeToast} />
    </div>
  );
}
