/**
 * Report export utilities for code review results
 */

import { UnifiedReport, ReviewFinding } from '../api/types';
import { findingToMarkdown } from './clipboardUtils';

/**
 * Export report to Markdown format
 */
export function exportToMarkdown(report: UnifiedReport): string {
  const lines: string[] = [];

  // Header
  lines.push('# Code Review Report');
  lines.push('');
  lines.push(`**Swarm ID:** ${report.swarm_id}`);
  lines.push(`**Target:** ${report.target_path}`);
  lines.push(`**Date:** ${new Date(report.created_at).toLocaleString()}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Total Findings:** ${report.total_findings}`);
  lines.push(`- **Critical:** ${report.critical_findings.length}`);
  lines.push(`- **High:** ${report.high_findings.length}`);
  lines.push(`- **Medium:** ${report.medium_findings.length}`);
  lines.push(`- **Low:** ${report.low_findings.length}`);
  lines.push(`- **Info:** ${report.info_findings.length}`);
  lines.push(`- **Duplicates Removed:** ${report.duplicates_removed}`);
  lines.push('');

  // Reviewers
  lines.push('### Reviewers');
  lines.push('');
  if (report.reviewers_completed.length > 0) {
    lines.push(`- **Completed:** ${report.reviewers_completed.join(', ')}`);
  }
  if (report.reviewers_failed.length > 0) {
    lines.push(`- **Failed:** ${report.reviewers_failed.join(', ')}`);
  }
  lines.push('');

  // Findings by category
  lines.push('### Findings by Category');
  lines.push('');
  for (const [category, count] of Object.entries(report.findings_by_category)) {
    lines.push(`- ${category}: ${count}`);
  }
  lines.push('');

  // All findings grouped by severity
  const allFindings = [
    ...report.critical_findings,
    ...report.high_findings,
    ...report.medium_findings,
    ...report.low_findings,
    ...report.info_findings,
  ];

  if (allFindings.length > 0) {
    lines.push('## Findings');
    lines.push('');

    for (const finding of allFindings) {
      lines.push('---');
      lines.push('');
      lines.push(findingToMarkdown(finding));
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by Parallel Review Swarm*');

  return lines.join('\n');
}

/**
 * Trigger file download in browser
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.style.display = 'none';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

/**
 * Export report to Markdown file
 */
export function downloadMarkdownReport(report: UnifiedReport): void {
  const content = exportToMarkdown(report);
  const date = new Date().toISOString().split('T')[0];
  const filename = `code-review-${report.swarm_id}-${date}.md`;
  downloadFile(content, filename, 'text/markdown');
}

/**
 * Export report to PDF using browser print
 */
export function exportToPDF(report: UnifiedReport): void {
  const content = exportToMarkdown(report);

  // Create a new window with the content for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    console.error('Failed to open print window');
    return;
  }

  // Convert markdown to basic HTML
  const htmlContent = markdownToBasicHtml(content);

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Code Review Report - ${report.swarm_id}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.6;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          color: #333;
        }
        h1 { color: #1a1a1a; border-bottom: 2px solid #333; padding-bottom: 10px; }
        h2 { color: #2a2a2a; margin-top: 30px; }
        h3 { color: #3a3a3a; }
        pre {
          background: #f5f5f5;
          padding: 15px;
          border-radius: 5px;
          overflow-x: auto;
          font-size: 13px;
        }
        code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; }
        hr { border: none; border-top: 1px solid #ddd; margin: 30px 0; }
        ul { padding-left: 20px; }
        @media print {
          body { padding: 0; }
          pre { page-break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      ${htmlContent}
    </body>
    </html>
  `);

  printWindow.document.close();

  // Wait for content to load then print
  printWindow.onload = () => {
    printWindow.print();
  };
}

/**
 * Convert basic Markdown to HTML
 */
function markdownToBasicHtml(markdown: string): string {
  return markdown
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Code blocks
    .replace(/```[\s\S]*?\n([\s\S]*?)```/g, '<pre><code>$1</code></pre>')
    // Lists
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
    // Horizontal rules
    .replace(/^---$/gm, '<hr>')
    // Paragraphs (lines with content)
    .replace(/^(?!<[hul]|<li|<pre|<hr)(.+)$/gm, '<p>$1</p>')
    // Clean up empty paragraphs
    .replace(/<p><\/p>/g, '')
    // Line breaks
    .replace(/\n\n/g, '\n');
}
